# Generated by Django 2.1.4 on 2019-01-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_libraryuser_editions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='editions',
            field=models.ManyToManyField(to='schol_library.Edition', verbose_name='издания для библиотекоря'),
        ),
    ]
