# Generated by Django 2.1.4 on 2019-01-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190125_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='editions',
            field=models.ManyToManyField(related_name='editions_s', to='schol_library.Edition', verbose_name='издания для библиотекоря'),
        ),
    ]
