# Generated by Django 2.1.4 on 2019-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0008_edition_isbn'),
        ('account', '0005_auto_20190125_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='edition',
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='editions',
            field=models.ManyToManyField(to='schol_library.Edition', verbose_name='издания для библиотекоря'),
        ),
    ]
