# Generated by Django 2.1.4 on 2019-02-01 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190128_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstoedit',
            options={'verbose_name': 'Доступ для редактирования', 'verbose_name_plural': 'Доступы для редактирования'},
        ),
        migrations.AlterField(
            model_name='accesstoedit',
            name='edit_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет доступа'), (1, 'Есть доступ')], default=0, verbose_name='статус редактирования'),
        ),
    ]
