# Generated by Django 2.1.4 on 2019-02-13 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
     #   ('portfoli', '0001_initial'),
        ('account', '0008_auto_20190201_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('role', models.SmallIntegerField(blank=True, choices=[(0, 'Нет роли'), (1, 'Бибилотекарь'), (2, 'Зам директора по учебной работе'), (3, 'Зав библиотеки')], default=0)),
                ('data_appointment', models.DateTimeField(blank=True, verbose_name='Дата назначения на должность')),
                ('data_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания на должности')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Журнал назначений',
                'verbose_name_plural': 'Журналы назначении',
            },
        ),
    ]
