# Generated by Django 2.1.4 on 2019-02-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rolehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='editions',
            field=models.ManyToManyField(blank=True, null=True, to='schol_library.Edition', verbose_name='издания для библиотекоря'),
        ),
    ]
