# Generated by Django 2.1.4 on 2019-02-14 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20190213_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libraryuser',
            name='role',
        ),
    ]
