# Generated by Django 2.1.4 on 2019-02-18 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20190214_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolehistory',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='роль'),
        ),
    ]
