# Generated by Django 2.1.4 on 2019-02-19 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20190218_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolehistory',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='роль'),
        ),
    ]
