# Generated by Django 2.1.4 on 2019-02-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20190219_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryuser',
            name='editions',
            field=models.ManyToManyField(blank=True, to='schol_library.Edition', verbose_name='издания для библиотекоря'),
        ),
    ]
