# Generated by Django 2.1.4 on 2019-02-19 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20190219_1351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryuser',
            options={'verbose_name': 'Портфолио Ekitaphana', 'verbose_name_plural': 'Портфолии Ekitaphana'},
        ),
    ]
