# Generated by Django 2.2 on 2019-04-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_remove_libraryuser_editions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageCabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_ru', models.CharField(default='', max_length=500, verbose_name='Название')),
                ('name_kk', models.CharField(blank=True, default='', max_length=500, verbose_name='Название')),
                ('name_en', models.CharField(blank=True, default='', max_length=500, verbose_name='Название')),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'verbose_name': 'Страница кабинета для доступа',
                'verbose_name_plural': 'Страницы кабинета для доступа',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='libraryuser',
            name='close_cabinet',
            field=models.ManyToManyField(to='account.PageCabinet', verbose_name='Страницы которым закрыт доступ'),
        ),
    ]
