# Generated by Django 2.2 on 2019-09-05 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
   #     ('portfoli', '0068_auto_20190905_1433'),
        ('account', '0019_auto_20190527_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryuser',
            name='create_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.AlmaMater'),
        ),
    ]
