# Generated by Django 2.2 on 2019-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0020_libraryuser_create_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoedit',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='pagecabinet',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='rolehistory',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
    ]
