# Generated by Django 2.2 on 2019-12-25 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
      #  ('portfoli', '0086_auto_20191225_1016'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0021_auto_20191016_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoedit',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', unique=True, verbose_name='школа'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='libraryuser',
        #     unique_together={('user', 'create_school')},
        # ),
    ]
