# Generated by Django 2.2 on 2019-12-25 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20191016_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoedit',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', unique=True, verbose_name='школа'),
        ),
    ]
