# Generated by Django 2.2 on 2019-12-25 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20191225_1152'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='libraryuser',
        #     unique_together=set(),
        # ),
    ]
