# Generated by Django 2.2 on 2019-12-25 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20191225_1218'),
        ('account', '0022_auto_20191225_1221'),
        ('account', '0023_auto_20191225_1153'),
    ]

    operations = [
    ]
