# Generated by Django 2.2 on 2020-04-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_merge_20191225_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoedit',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа'),
        ),
    ]
