# Generated by Django 2.2 on 2020-04-22 05:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0025_auto_20200405_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoedit',
            name='date_invoice',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата для накладных'),
            preserve_default=False,
        ),
    ]
