# Generated by Django 2.2 on 2020-04-22 05:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0026_accesstoedit_date_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoedit',
            name='date_invoice',
            field=models.DateField(blank=True, default=datetime.date(2020, 4, 22), verbose_name='Дата для накладных'),
        ),
    ]
