# Generated by Django 2.2 on 2020-04-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0028_auto_20200422_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstoedit',
            name='status_12',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет доступа'), (1, 'Есть доступ')], default=0, verbose_name='статус для первой и второй страницы'),
        ),
    ]
