# Generated by Django 2.2 on 2020-04-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0029_accesstoedit_status_12'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesstoedit',
            name='status_12',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Нет доступа'), (1, 'Есть доступ')], default=1, verbose_name='статус для первой и второй страницы'),
        ),
    ]
