# Generated by Django 2.2 on 2021-04-29 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0002_auto_20210407_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='klass',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='obl',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['sort']},
        ),
        migrations.AlterModelOptions(
            name='scale',
            options={'ordering': ['sort']},
        ),

        migrations.AlterField(
            model_name='almamater',
            name='image',
            field=models.ImageField(default='nophoto.png', upload_to='usr/2021-04-29/almamater'),
        ),
        migrations.AlterField(
            model_name='aspirantprivate',
            name='image',
            field=models.ImageField(upload_to='usr/2021-04-29/private_docs/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='image',
            field=models.ImageField(null=True, upload_to='usr/common/2021-04-29/coursetype', verbose_name='Scan view'),
        ),
        migrations.AlterField(
            model_name='notificationfile',
            name='file',
            field=models.FileField(upload_to='usr/2021-04-29/notifications'),
        ),




        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(upload_to='usr/2021-04-29/protocol'),
        ),
        migrations.AlterField(
            model_name='registerschool',
            name='image',
            field=models.ImageField(upload_to='usr/2021-04-29/responisble_statement', verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='image',
            field=models.ImageField(default='/static/images/nophoto.png', upload_to='usr/common/2021-04-29/school_types'),
        ),
        migrations.AlterField(
            model_name='testschool',
            name='image',
            field=models.ImageField(default='/static/images/nophoto.png', upload_to='usr/2021-04-29/testalmamater'),
        ),


    ]
