# Generated by Django 2.2 on 2021-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0003_auto_20210429_0855'),
    ]

    operations = [

    ]
