# Generated by Django 2.2 on 2021-05-03 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0007_auto_20210503_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='klass',
            name='klass_type',
            field=models.IntegerField(default=2),
        ),
    ]
