# Generated by Django 2.2 on 2021-05-06 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0009_auto_20210504_1056'),
    ]

    operations = [

        migrations.AlterField(
            model_name='almamater',
            name='image',
            field=models.ImageField(default='nophoto.png', upload_to='usr/2021-05-06/almamater'),
        ),
        migrations.AlterField(
            model_name='aspirantprivate',
            name='image',
            field=models.ImageField(upload_to='usr/2021-05-06/private_docs/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='image',
            field=models.ImageField(null=True, upload_to='usr/common/2021-05-06/coursetype', verbose_name='Scan view'),
        ),
        migrations.AlterField(
            model_name='notificationfile',
            name='file',
            field=models.FileField(upload_to='usr/2021-05-06/notifications'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='file',
            field=models.FileField(upload_to='usr/2021-05-06/protocol'),
        ),
        migrations.AlterField(
            model_name='registerschool',
            name='image',
            field=models.ImageField(upload_to='usr/2021-05-06/responisble_statement', verbose_name='Приказ'),
        ),
        migrations.AlterField(
            model_name='schooltype',
            name='image',
            field=models.ImageField(default='/static/images/nophoto.png', upload_to='usr/common/2021-05-06/school_types'),
        ),
        migrations.AlterField(
            model_name='testschool',
            name='image',
            field=models.ImageField(default='/static/images/nophoto.png', upload_to='usr/2021-05-06/testalmamater'),
        ),
    ]
