# Generated by Django 2.1.4 on 2019-01-16 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
     #   ('portfoli', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_ru', models.CharField(default='', max_length=500)),
                ('name_kk', models.CharField(blank=True, default='', max_length=500)),
                ('name_en', models.CharField(blank=True, default='', max_length=500)),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancellationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_ru', models.CharField(default='', max_length=500)),
                ('name_kk', models.CharField(blank=True, default='', max_length=500)),
                ('name_en', models.CharField(blank=True, default='', max_length=500)),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='название')),
                ('author', models.CharField(blank=True, max_length=200, verbose_name='автор')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='издатель')),
                ('publish_date', models.DateField(blank=True, verbose_name='дата публикации')),
                ('series_by_year', models.DateField(blank=True, verbose_name='серия по годам')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='дата поставки')),
                ('delivery_document', models.CharField(blank=True, max_length=200, verbose_name='документ поставки')),
                ('amount', models.FloatField(blank=True, verbose_name='сумма')),
                ('cancellation_date', models.DateField(blank=True, verbose_name='дата отмены')),
                ('quality_claims', models.CharField(blank=True, max_length=200, verbose_name='претензии по качеству')),
                ('mistakes', models.CharField(blank=True, max_length=200, verbose_name='ошибки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='editions/', verbose_name='изображение')),
                ('application_recommendations', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.ApplicationR', verbose_name='рекомендации по применению')),
                ('cancellation_reason', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.CancellationReason', verbose_name='причина отмены')),
            ],
            options={
                'verbose_name': 'издание',
                'verbose_name_plural': 'издания',
            },
        ),
        migrations.CreateModel(
            name='FundingСycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_ru', models.CharField(default='', max_length=500)),
                ('name_kk', models.CharField(blank=True, default='', max_length=500)),
                ('name_en', models.CharField(blank=True, default='', max_length=500)),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyDirections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_ru', models.CharField(default='', max_length=500)),
                ('name_kk', models.CharField(blank=True, default='', max_length=500)),
                ('name_en', models.CharField(blank=True, default='', max_length=500)),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UMK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_ru', models.CharField(default='', max_length=500)),
                ('name_kk', models.CharField(blank=True, default='', max_length=500)),
                ('name_en', models.CharField(blank=True, default='', max_length=500)),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='edition',
            name='funding_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol_library.FundingСycle', verbose_name='цикл финансирования'),
        ),
        migrations.AddField(
            model_name='edition',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс'),
        ),
        migrations.AddField(
            model_name='edition',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык'),
        ),
        migrations.AddField(
            model_name='edition',
            name='metodology_complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.UMK', verbose_name='методологический комплекс'),
        ),
        migrations.AddField(
            model_name='edition',
            name='study_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
        migrations.AddField(
            model_name='edition',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Subject', verbose_name='предмет'),
        ),
    ]
