# Generated by Django 2.1.4 on 2019-01-21 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    #    ('portfoli', '0001_initial'),
        ('schol_library', '0004_auto_20190118_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmountBooksStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('on_hands', models.IntegerField(blank=True, verbose_name='на руках')),
                ('in_warehouse', models.IntegerField(blank=True, verbose_name='на складе')),
                ('amount', models.IntegerField(blank=True, verbose_name='общее количество книг в школе')),
                ('amount_students', models.IntegerField(blank=True, default=0, verbose_name='общее количество учеников')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
            ],
            options={
                'verbose_name': 'общее количество книг',
                'verbose_name_plural': 'общее количество книг',
            },
        ),
        migrations.CreateModel(
            name='SchoolTitul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('liter', models.CharField(blank=True, max_length=3, verbose_name='Название класса')),
                ('students', models.IntegerField(blank=True, verbose_name='количество учащихся')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('study_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения')),
                ('year', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='дата обучения')),
            ],
            options={
                'verbose_name': 'Титул школы',
                'verbose_name_plural': 'Титулы школы',
            },
        ),
        migrations.RemoveField(
            model_name='amountbooks',
            name='school',
        ),
        migrations.DeleteModel(
            name='AmountBooks',
        ),
    ]
