# Generated by Django 2.1.4 on 2019-01-21 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0005_auto_20190121_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltitul',
            name='study_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
    ]
