# Generated by Django 2.1.4 on 2019-02-01 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0008_edition_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='series_by_year',
        ),
    ]
