# Generated by Django 2.1.4 on 2019-02-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0009_remove_edition_series_by_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='series_by_year',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='серия по годам'),
        ),
    ]
