# Generated by Django 2.1.4 on 2019-02-19 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0012_auto_20190219_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitul',
            name='liter',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Liter', verbose_name='Название класса'),
        ),
    ]
