# Generated by Django 2.1.4 on 2019-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0013_schooltitul_liter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liter',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=3, verbose_name='Литер класса'),
        ),
    ]
