# Generated by Django 2.1.4 on 2019-02-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0014_auto_20190219_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liter',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='liter',
            name='uid',
        ),
    ]
