# Generated by Django 2.1.4 on 2019-02-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0015_auto_20190219_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='publish_date',
            field=models.DateField(blank=True, verbose_name='год издания'),
        ),
    ]
