# Generated by Django 2.1.4 on 2019-02-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
     #   ('portfoli', '0001_initial'),
        ('schol_library', '0016_auto_20190221_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('students', models.IntegerField(blank=True, verbose_name='количество учащихся')),
                ('planned_quantity', models.IntegerField(blank=True, verbose_name='плановое количество учащихся')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс')),
                ('language', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения')),
                ('liter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Liter', verbose_name='Название класса')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('school_titul', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.SchoolTitul', verbose_name='титул школы')),
                ('study_direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения')),
                ('year', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='учебный год\u2028')),
            ],
            options={
                'verbose_name': 'плановый титул школы',
                'verbose_name_plural': 'плановый титульный список',
                'ordering': ['school', 'school_titul'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('year', models.SmallIntegerField(blank=True, verbose_name='год')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Не показывать'), (1, 'Показывать')])),
            ],
            options={
                'verbose_name': 'Год',
                'verbose_name_plural': 'Года',
            },
        ),
    ]
