# Generated by Django 2.2 on 2019-05-15 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('schol_library', '0018_auto_20190221_1107'), ('schol_library', '0019_auto_20190222_1249'), ('schol_library', '0020_auto_20190227_1534'), ('schol_library', '0021_auto_20190227_1536'), ('schol_library', '0022_auto_20190227_1537'), ('schol_library', '0023_auto_20190227_1554'), ('schol_library', '0024_auto_20190227_1557'), ('schol_library', '0025_auto_20190227_1606'), ('schol_library', '0026_auto_20190227_1623'), ('schol_library', '0027_auto_20190227_1654'), ('schol_library', '0028_schooltitul_class_teacher'), ('schol_library', '0029_auto_20190304_1106'), ('schol_library', '0030_auto_20190311_1544'), ('schol_library', '0031_auto_20190311_1640'), ('schol_library', '0032_auto_20190311_1656'), ('schol_library', '0033_auto_20190311_1658'), ('schol_library', '0034_auto_20190311_1831'), ('schol_library', '0035_auto_20190314_1127'), ('schol_library', '0036_auto_20190318_1100'), ('schol_library', '0037_auto_20190318_1650'), ('schol_library', '0038_auto_20190328_1244'), ('schol_library', '0039_auto_20190328_1301'), ('schol_library', '0040_auto_20190328_1303'), ('schol_library', '0041_auto_20190328_2130'), ('schol_library', '0041_auto_20190328_1306'), ('schol_library', '0042_merge_20190328_2155'), ('schol_library', '0043_auto_20190402_1524'), ('schol_library', '0044_liter_sort'), ('schol_library', '0045_setumk'), ('schol_library', '0046_briefcase_editionbriefcase_parameter'), ('schol_library', '0047_briefcase_klass'), ('schol_library', '0048_plannedtitle_briefcase'), ('schol_library', '0049_auto_20190418_1104'), ('schol_library', '0050_auto_20190419_1124'), ('schol_library', '0051_auto_20190429_1249'), ('schol_library', '0052_auto_20190502_1528'), ('schol_library', '0053_auto_20190503_1106'), ('schol_library', '0054_planeditionteacher_year')]

    dependencies = [
        ('schol_library', '0017_plannedtitle_year'),
     #   ('portfoli', '0044_auto_20190502_1528'),
      #  ('portfoli', '0045_auto_20190506_0957'),
     #   ('portfoli', '0035_auto_20190411_1038'),
    #    ('portfoli', '0037_auto_20190417_1542'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtitle',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа'),
        ),
        migrations.AlterModelOptions(
            name='plannedtitle',
            options={'ordering': ['school', 'klass'], 'verbose_name': 'плановый титул школы', 'verbose_name_plural': 'плановый титульный список'},
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='liter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Liter', verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='study_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
        migrations.AlterField(
            model_name='year',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Не показывать'), (1, 'Показывать')], null=True),
        ),
        migrations.RenameField(
            model_name='year',
            old_name='year',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='год'),
        ),
        migrations.CreateModel(
            name='AuthorEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=150, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Автор издетельства',
                'verbose_name_plural': 'Авторы издательства',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PublisherEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name_en', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название издательства')),
                ('name_kk', models.CharField(blank=True, max_length=150, null=True, verbose_name='Название издательства')),
                ('name_ru', models.CharField(max_length=150, verbose_name='Название издательства')),
                ('sort', models.IntegerField(default=500)),
                ('uid', models.CharField(blank=True, default='', max_length=36, null=True)),
            ],
            options={
                'verbose_name': 'Издетельство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.RemoveField(
            model_name='edition',
            name='author',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='series_by_year',
        ),
        migrations.AlterField(
            model_name='edition',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата отмены'),
        ),
        migrations.AddField(
            model_name='edition',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.PublisherEdition', verbose_name='издатель'),
        ),
        migrations.AddField(
            model_name='edition',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.AuthorEdition', verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='edition',
            name='publish_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_date', to='schol_library.Year', verbose_name='год издания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edition',
            name='series_by_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_by_year', to='schol_library.Year', verbose_name='серия по годам'),
        ),
        migrations.RemoveField(
            model_name='edition',
            name='name',
        ),
        migrations.AddField(
            model_name='edition',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='schooltitul',
            name='class_teacher',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='классный руководитель'),
        ),
        migrations.AlterField(
            model_name='applicationr',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='applicationr',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='applicationr',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fundingсycle',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fundingсycle',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fundingсycle',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirections',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirections',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirections',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='umk',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='umk',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='umk',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='metodology_complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.UMK', verbose_name='Учебно-методический комплекс'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='schooltitul',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
        migrations.AlterModelOptions(
            name='umk',
            options={'ordering': ['name_ru']},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['klass__id', 'subject__name', 'name'], 'verbose_name': 'издание', 'verbose_name_plural': 'издания'},
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='students',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество учащихся'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='liter',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=70, verbose_name='название портфеля')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='описание')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('klass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
                'ordering': ['school', 'author'],
            },
        ),
        migrations.AddField(
            model_name='plannedtitle',
            name='briefcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_tituls', to='schol_library.Briefcase', verbose_name='Портфель'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.Language', verbose_name='язык обучения'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='study_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
        migrations.CreateModel(
            name='EditionBriefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('surplus', models.SmallIntegerField(default=0, verbose_name='Префицит')),
                ('briefcase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='schol_library.Briefcase', verbose_name='Портфель')),
                ('edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Издание портфеля',
                'verbose_name_plural': 'Издания портфелей',
                'ordering': ['briefcase'],
            },
        ),
        migrations.CreateModel(
            name='PlanEditionTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('quantity', models.SmallIntegerField(default=100, verbose_name='Количество')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='Издание')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.DateObjects', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Издание для учителей',
                'verbose_name_plural': 'Издания для учителей',
                'ordering': ['edition'],
            },
        ),
    ]
