# Generated by Django 2.1.4 on 2019-02-22 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0018_auto_20190221_1107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plannedtitle',
            options={'ordering': ['school', 'klass'], 'verbose_name': 'плановый титул школы', 'verbose_name_plural': 'плановый титульный список'},
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='liter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Liter', verbose_name='Название класса'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='school',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='study_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
        migrations.AlterField(
            model_name='year',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Не показывать'), (1, 'Показывать')], null=True),
        ),
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='год'),
        ),
    ]
