# Generated by Django 2.2 on 2019-05-17 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0019_auto_20190517_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanEditionTeacher1',
        ),
    ]
