# Generated by Django 2.1.4 on 2019-02-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0019_auto_20190222_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Автор издетельства',
                'verbose_name_plural': 'Авторы издательства',
            },
        ),
        migrations.CreateModel(
            name='PublisherEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, verbose_name='Название издательства')),
            ],
            options={
                'verbose_name': 'Издетельство',
                'verbose_name_plural': 'Издательства',
            },
        ),
        migrations.RemoveField(
            model_name='edition',
            name='author',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='series_by_year',
        ),
        migrations.AlterField(
            model_name='edition',
            name='cancellation_date',
            field=models.DateField(blank=True, null=True, verbose_name='дата отмены'),
        ),
    ]
