# Generated by Django 2.1.4 on 2019-02-27 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0020_auto_20190227_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.AuthorEdition', verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='edition',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.PublisherEdition', verbose_name='издатель'),
        ),
    ]
