# Generated by Django 2.1.4 on 2019-02-27 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0022_auto_20190227_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='publish_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publish_date', to='schol_library.Year', verbose_name='год издания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edition',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.PublisherEdition', verbose_name='издатель'),
            preserve_default=False,
        ),
    ]
