# Generated by Django 2.2 on 2019-07-30 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0023_auto_20190729_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editioninvoice',
            options={'verbose_name': 'Книги накладной в издательстве', 'verbose_name_plural': 'Книги наглодной в издательстве'},
        ),
        migrations.AlterField(
            model_name='provider',
            name='edition_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_query_name='providers', to='schol_library.EditionInvoice'),
        ),
    ]
