# Generated by Django 2.1.4 on 2019-02-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0024_auto_20190227_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='year',
            old_name='name',
            new_name='year',
        ),
        migrations.AlterField(
            model_name='edition',
            name='author',
            field=models.ForeignKey(blank=True,null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.AuthorEdition', verbose_name='автор'),
            preserve_default=False,
        ),
    ]
