# Generated by Django 2.2 on 2019-08-05 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0025_auto_20190730_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editioninvoice',
            name='procurement_plan',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='date',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='edition_invoice',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='quantity',
        ),
        migrations.AddField(
            model_name='editioninvoice',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='заполнитель'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, max_length=300, verbose_name='Номер счет фактуры'),
        ),
    ]
