# Generated by Django 2.1.4 on 2019-02-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0025_auto_20190227_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='series_by_year',
        ),
    ]
