# Generated by Django 2.2 on 2019-08-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0027_invoice_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='editioninvoice',
            name='planned_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество'),
        ),
    ]
