# Generated by Django 2.2 on 2019-08-08 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0028_editioninvoice_planned_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='date_extracts',
            field=models.DateField(blank=True, null=True, verbose_name='дата выписки поставщика'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='freight_carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_carrier_invoices', to='schol_library.Provider', verbose_name='Грузоперевозчик'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='power_of_attorney',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='доверенность'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_invoices', to='schol_library.Provider', verbose_name='Грузоотправитель'),
        ),
        migrations.AlterField(
            model_name='editioninvoice',
            name='planned_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='плановое количество'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_invoices', to='schol_library.Provider', verbose_name='Поставщик'),
        ),
    ]
