# Generated by Django 2.1.4 on 2019-03-04 05:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0028_schooltitul_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltitul',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='классный руководитель'),
        ),
    ]
