# Generated by Django 2.1.4 on 2019-03-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0029_auto_20190304_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='name',
        ),
        migrations.AddField(
            model_name='edition',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='name_ru',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='sort',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='edition',
            name='uid',
            field=models.CharField(blank=True, default='', max_length=36, null=True),
        ),
    ]
