# Generated by Django 2.2 on 2019-08-12 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0030_auto_20190812_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Номер счет фактуры'),
        ),
    ]
