# Generated by Django 2.2 on 2019-08-12 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
    #    ('portfoli', '0060_auto_20190812_1150'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0030_auto_20190812_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editioninvoice',
            options={'verbose_name': 'Книги накладной в издательстве', 'verbose_name_plural': 'Книги наглодных в издательстве'},
        ),
        migrations.AlterField(
            model_name='editioninvoice',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Invoice', verbose_name='Накладная'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Номер счет фактуры'),
        ),
        migrations.CreateModel(
            name='PaperInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.CharField(blank=True, default='', max_length=300, verbose_name='Номер счет фактуры')),
                ('power_of_attorney', models.CharField(blank=True, max_length=300, null=True, verbose_name='доверенность')),
                ('date_extracts', models.DateField(blank=True, null=True, verbose_name='дата выписки поставщика')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('freight_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_carrier_p_invoices', to='schol_library.Provider', verbose_name='Грузоперевозчик')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_p_invoices', to='schol_library.Provider', verbose_name='Поставщик')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.PublisherEdition', verbose_name='издательство')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('shipper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_p_invoices', to='schol_library.Provider', verbose_name='Грузоотправитель')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schol_library.Year')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EditionPaperInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='количество')),
                ('planned_quantity', models.IntegerField(blank=True, default=0, verbose_name='плановое количество')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='издание')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.PaperInvoice', verbose_name='Накладная')),
            ],
            options={
                'verbose_name': 'Книги для бумажной накладной в издательстве',
                'verbose_name_plural': 'Книги для бумажных наглодных в издательстве',
            },
        ),
    ]
