# Generated by Django 2.1.4 on 2019-03-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0031_auto_20190311_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edition',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='sort',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='uid',
        ),
        migrations.AddField(
            model_name='edition',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='название'),
        ),
    ]
