# Generated by Django 2.2 on 2019-08-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0031_auto_20190812_1413'),
        ('schol_library', '0031_auto_20190812_1503'),
    ]

    operations = [
    ]
