# Generated by Django 2.2 on 2019-08-13 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0032_merge_20190813_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperinvoice',
            options={'verbose_name': 'бумажная накладная', 'verbose_name_plural': 'бумажные накладные'},
        ),
    ]
