# Generated by Django 2.2 on 2019-08-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0033_auto_20190813_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='name_en',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование поставщика'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_kk',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование поставщика'),
        ),
        migrations.AddField(
            model_name='provider',
            name='name_ru',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование поставщика'),
        ),
    ]
