# Generated by Django 2.1.4 on 2019-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0034_auto_20190311_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationr',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='applicationr',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='applicationr',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cancellationreason',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fundingсycle',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fundingсycle',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fundingсycle',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publisheredition',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publisheredition',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='publisheredition',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirections',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirections',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='studydirections',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='umk',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='umk',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='umk',
            name='name_ru',
            field=models.CharField(default='', max_length=500, verbose_name='Название'),
        ),
    ]
