# Generated by Django 2.2 on 2019-08-13 07:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0032_merge_20190813_0907'),
        ('schol_library', '0034_auto_20190813_0953'),
    ]

    operations = [
    ]
