# Generated by Django 2.1.4 on 2019-03-18 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0035_auto_20190314_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='metodology_complex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.UMK', verbose_name='Учебно-методический комплекс'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
        migrations.AlterField(
            model_name='publisheredition',
            name='name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='publisheredition',
            name='name_kk',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='publisheredition',
            name='name_ru',
            field=models.CharField(max_length=150, verbose_name='Название издательства'),
        ),
        migrations.AlterField(
            model_name='schooltitul',
            name='year',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
    ]
