# Generated by Django 2.2 on 2019-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0035_merge_20190813_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='number_provider',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Номер поставщика'),
        ),
        migrations.AddField(
            model_name='paperinvoice',
            name='number_provider',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Номер поставщика'),
        ),
    ]
