# Generated by Django 2.1.4 on 2019-03-18 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0036_auto_20190318_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['klass', 'subject', 'publisher'], 'verbose_name': 'издание', 'verbose_name_plural': 'издания'},
        ),
    ]
