# Generated by Django 2.2 on 2019-08-14 08:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0035_merge_20190813_1356'),
        ('schol_library', '0037_auto_20190814_0936'),
    ]

    operations = [
    ]
