# Generated by Django 2.1.4 on 2019-03-28 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0038_auto_20190328_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umk',
            options={'ordering': ['name_ru']},
        ),
    ]
