# Generated by Django 2.2 on 2019-08-14 09:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0039_auto_20190814_1418'),
        ('schol_library', '0039_auto_20190814_1426'),
    ]

    operations = [
    ]
