# Generated by Django 2.1.4 on 2019-03-28 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0039_auto_20190328_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['klass__id', 'subject__name_ru', 'name'], 'verbose_name': 'издание',
                     'verbose_name_plural': 'издания'},
        ),
    ]
