# Generated by Django 2.1.4 on 2019-03-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0040_auto_20190328_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authoredition',
            options={'ordering': ['name'], 'verbose_name': 'Автор издетельства', 'verbose_name_plural': 'Авторы издательства'},
        ),
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['klass__id', 'subject__name', 'name'], 'verbose_name': 'издание', 'verbose_name_plural': 'издания'},
        ),
    ]
