# Generated by Django 2.2 on 2019-08-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
    #    ('portfoli', '0063_auto_20190814_0936'),
        ('schol_library', '0041_auto_20190814_1531'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='invoice',
        #     name='confidant',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
        #                             to='portfoli.Portfolio', verbose_name='Доверенное лицо'),
        # ),
        # migrations.AddField(
        #     model_name='invoice',
        #     name='date_power_of_attorney',
        #     field=models.DateField(blank=True, null=True, verbose_name='Дата доверености'),
        # ),
    ]
