# Generated by Django 2.1.4 on 2019-03-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0041_auto_20190328_2130'),
        ('schol_library', '0041_auto_20190328_1306'),
    ]

    operations = [
    ]
