# Generated by Django 2.1.4 on 2019-04-02 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0042_merge_20190328_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtitle',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='students',
            field=models.IntegerField(blank=True, null=True, verbose_name='количество учащихся'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
    ]
