# Generated by Django 2.2 on 2019-08-22 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0042_auto_20190814_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinvoice',
            name='idx',
            field=models.CharField(blank=True, default='Нету номера на накладной', max_length=300, verbose_name='Номер накладной'),
        ),
    ]
