# Generated by Django 2.1.4 on 2019-04-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0043_auto_20190402_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='liter',
            name='sort',
            field=models.IntegerField(default=500),
        ),
    ]
