# Generated by Django 2.2 on 2019-08-29 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0043_paperinvoice_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionpaperinvoice',
            name='edition',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='издание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editionpaperinvoice',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.PaperInvoice', verbose_name='Накладная'),
            preserve_default=False,
        ),
    ]
