# Generated by Django 2.2 on 2019-08-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0045_remove_editionpaperinvoice_planned_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editionpaperinvoice',
            unique_together={('invoice', 'edition')},
        ),
    ]
