# Generated by Django 2.2 on 2019-04-11 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0045_setumk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Briefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='название портфеля')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
            ],
            options={
                'verbose_name': 'Портфель',
                'verbose_name_plural': 'Портфели',
                'ordering': ['school', 'author'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefcase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='schol_library.Briefcase', verbose_name='Портфель')),
                ('plan_titul', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='schol_library.PlannedTitle', verbose_name='плановый титул школы')),
            ],
            options={
                'verbose_name': 'Параметры Портфеля',
                'verbose_name_plural': 'Параметры Портфелей',
                'ordering': ['plan_titul', 'briefcase'],
            },
        ),
        migrations.CreateModel(
            name='EditionBriefcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('surplus', models.SmallIntegerField(default=100, verbose_name='Префицит')),
                ('briefcase', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='schol_library.Briefcase', verbose_name='Портфель')),
                ('edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='Издание')),
            ],
            options={
                'verbose_name': 'Издание портфеля',
                'verbose_name_plural': 'Издания портфелей',
                'ordering': ['briefcase'],
            },
        ),
    ]
