# Generated by Django 2.2 on 2019-09-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    #    ('portfoli', '0069_auto_20190906_1642'),
        ('schol_library', '0046_auto_20190829_1659'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-date', 'id'], 'verbose_name': 'накладная', 'verbose_name_plural': 'накладные'},
        ),
        migrations.CreateModel(
            name='IncomeExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('registrator_id', models.UUIDField(blank=True, verbose_name='id зарегистрированного типа')),
                ('object_id', models.PositiveIntegerField()),
                ('type_of_movement', models.SmallIntegerField(blank=True, verbose_name='вид движения')),
                ('quantity', models.IntegerField(blank=True, verbose_name='количество')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('edition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schol_library.Edition')),
                ('school_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.AlmaMater', verbose_name='школа')),
            ],
            options={
                'verbose_name': 'приход/расход',
                'verbose_name_plural': 'приходы/расходы',
            },
        ),
    ]
