# Generated by Django 2.2 on 2019-04-17 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
     #   ('portfoli', '0037_auto_20190417_1542'),
        ('schol_library', '0046_briefcase_editionbriefcase_parameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefcase',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс'),
        ),
    ]
