# Generated by Django 2.2 on 2019-04-18 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0047_briefcase_klass'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannedtitle',
            name='briefcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_tituls', to='schol_library.Briefcase', verbose_name='Портфель'),
        ),
    ]
