# Generated by Django 2.2 on 2019-09-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0047_auto_20190906_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomeexpense',
            name='registrator_id',
        ),
    ]
