# Generated by Django 2.2 on 2019-04-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0048_plannedtitle_briefcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='briefcase',
            name='description',
            field=models.CharField(blank=True, max_length=20, verbose_name='описание'),
        ),
    ]
