# Generated by Django 2.2 on 2019-09-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0048_remove_incomeexpense_registrator_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editioninvoice',
            options={'ordering': ['id'], 'verbose_name': 'Книги накладной в издательстве', 'verbose_name_plural': 'Книги наглодных в издательстве'},
        ),
        migrations.AlterModelOptions(
            name='editionpaperinvoice',
            options={'ordering': ['id'], 'verbose_name': 'Книги для бумажной накладной в издательстве', 'verbose_name_plural': 'Книги для бумажных наглодных в издательстве'},
        ),
        migrations.AlterModelOptions(
            name='incomeexpense',
            options={'ordering': ['id'], 'verbose_name': 'приход/расход', 'verbose_name_plural': 'приходы/расходы'},
        ),
    ]
