# Generated by Django 2.2 on 2019-09-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0050_auto_20190910_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='paperinvoice',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
    ]
