# Generated by Django 2.2 on 2019-04-29 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0050_auto_20190419_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedtitle',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.Language', verbose_name='язык обучения'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='study_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
        migrations.AlterField(
            model_name='plannedtitle',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
    ]
