# Generated by Django 2.2 on 2019-09-17 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0052_auto_20190917_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 17, 17, 50, 4, 38329), null=True, verbose_name='время заявки'),
        ),
    ]
