# Generated by Django 2.2 on 2019-05-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0052_auto_20190502_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionbriefcase',
            name='surplus',
            field=models.SmallIntegerField(default=0, verbose_name='Префицит'),
        ),
    ]
