# Generated by Django 2.2 on 2019-09-22 04:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
     #   ('portfoli', '0073_auto_20190922_1049'),
        ('schol_library', '0053_auto_20190917_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 10, 49, 37, 455516), verbose_name='время заявки'),
        ),
        migrations.CreateModel(
            name='CheckidRequestEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 10, 49, 37, 456596), null=True, verbose_name='время просмотра')),
                ('check', models.BooleanField(blank=True, null=True, verbose_name='статус подверждение/отказ')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('request_edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.RequestEdition', verbose_name='Заявка')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school', to='portfoli.AlmaMater', verbose_name='Школа')),
            ],
            options={
                'verbose_name': 'Статус просмотра',
                'verbose_name_plural': 'Статусы просмотра',
                'ordering': ['id'],
                'unique_together': {('request_edition', 'school')},
            },
        ),
    ]
