# Generated by Django 2.2 on 2019-05-06 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [

        ('schol_library', '0053_auto_20190503_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='planeditionteacher',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
    ]
