# Generated by Django 2.2 on 2019-09-22 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0054_auto_20190922_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkidrequestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 10, 53, 37, 138958), null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 10, 53, 37, 137827), verbose_name='время заявки'),
        ),
        migrations.AlterUniqueTogether(
            name='checkidrequestedition',
            unique_together=set(),
        ),
    ]
