# Generated by Django 2.2 on 2019-09-22 04:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    #    ('portfoli', '0073_auto_20190922_1049'),
        ('schol_library', '0055_auto_20190922_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkidrequestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 10, 57, 45, 4214), null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 10, 57, 45, 3109), verbose_name='время заявки'),
        ),
        migrations.AlterUniqueTogether(
            name='checkidrequestedition',
            unique_together={('request_edition', 'school')},
        ),
        migrations.AlterUniqueTogether(
            name='requestedition',
            unique_together=set(),
        ),
    ]
