# Generated by Django 2.2 on 2019-09-22 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0056_auto_20190922_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkidrequestedition',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='checkidrequestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 11, 10, 4, 672484), null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 11, 10, 4, 671307), verbose_name='время заявки'),
        ),
    ]
