# Generated by Django 2.2 on 2019-09-22 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0057_auto_20190922_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkidrequestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 11, 44, 26, 721064), null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 11, 44, 26, 720087), verbose_name='время заявки'),
        ),
    ]
