# Generated by Django 2.2 on 2019-09-22 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0058_auto_20190922_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedition',
            name='checkid',
            field=models.BooleanField(blank=True, default=False, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='checkidrequestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 17, 29, 19, 729564), null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 22, 17, 29, 19, 728450), verbose_name='время заявки'),
        ),
    ]
