# Generated by Django 2.2 on 2019-09-23 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0059_auto_20190922_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkidrequestedition',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='время просмотра'),
        ),
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 23, 11, 12, 32, 868990), verbose_name='время заявки'),
        ),
    ]
