# Generated by Django 2.2 on 2019-10-03 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0061_auto_20190923_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 3, 17, 14, 20, 332876), verbose_name='время заявки'),
        ),
    ]
