# Generated by Django 2.2 on 2019-10-09 09:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0062_auto_20191003_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 9, 15, 13, 59, 247402),
                                       verbose_name='время заявки'),
        ),
    ]
