# Generated by Django 2.2 on 2019-10-09 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0063_auto_20191009_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 9, 15, 20, 11, 276317),
                                       verbose_name='время заявки'),
        ),
    ]
