# Generated by Django 2.2 on 2019-10-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0073_auto_20191010_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedition',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True,
                                       verbose_name='время заявки'),
        ),
    ]
