# Generated by Django 2.2 on 2019-10-16 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0074_auto_20191010_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='amountbooksstudents',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='applicationr',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='authoredition',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='briefcase',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='cancellationreason',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='checkidrequestedition',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='edition',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='editionbriefcase',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='editioncomplex',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='fundingсycle',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='numberbooks',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='paperinvoice',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='planeditionteacher',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='plannedtitle',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='provider',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='publisheredition',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='requestedition',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='schooltitul',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='studydirections',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='umk',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='year',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
    ]
