# Generated by Django 2.2 on 2019-11-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0075_auto_20191016_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='name',
            field=models.CharField(blank=True, max_length=500, verbose_name='название'),
        ),
    ]
