# Generated by Django 2.2 on 2019-12-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0076_auto_20191120_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinvoice',
            name='billing',
            field=models.BooleanField(blank=True, default=False, verbose_name='Списание'),
        ),
    ]
