# Generated by Django 2.2 on 2019-12-13 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
   #     ('portfoli', '0085_auto_20191213_1537'),
        ('schol_library', '0077_paperinvoice_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='date_delete')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('idx', models.CharField(blank=True, default='Нету номера на накладной', max_length=300, verbose_name='Номер накладной')),
                ('date', models.DateField(auto_now_add=True)),
                ('number', models.CharField(blank=True, default='', max_length=300, verbose_name='Номер счет фактуры')),
                ('quantity', models.IntegerField(blank=True, verbose_name='Количество')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='издание')),
                ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schol_library.Year')),
            ],
            options={
                'verbose_name': 'накладная на списывание',
                'verbose_name_plural': 'накладные на списывание',
                'ordering': ['edition'],
            },
        ),
    ]
