# Generated by Django 2.2 on 2019-12-25 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0078_billinginvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltitul',
            name='class_teacher',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='классный руководитель'),
        ),
    ]
