# Generated by Django 2.2 on 2020-01-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
     #   ('portfoli', '0087_auto_20200108_2123'),
        ('schol_library', '0079_auto_20191225_1016'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='numberbooks',
            unique_together={('school', 'edition')},
        ),
    ]
