# Generated by Django 2.2 on 2020-04-05 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0081_auto_20200405_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditionActWrite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Инвентарный номер')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='количество')),
                ('amount', models.IntegerField(blank=True, default=0, verbose_name='цена')),
                ('edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='издание')),
                ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.ActWriteOff', verbose_name='Акт на списание')),
            ],
            options={
                'verbose_name': 'Книги для бумажной накладной в издательстве',
                'verbose_name_plural': 'Книги для бумажных наглодных в издательстве',
                'ordering': ['id'],
                'unique_together': {('invoice', 'edition')},
            },
        ),
    ]
