# Generated by Django 2.2 on 2020-04-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0082_editionactwrite'),
    ]

    operations = [
        migrations.AddField(
            model_name='actwriteoff',
            name='members_of_commission',
            field=models.TextField(null=True, verbose_name='члены комиссии'),
        ),
    ]
