# Generated by Django 2.2 on 2020-04-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0083_actwriteoff_members_of_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actwriteoff',
            name='year',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='billing',
        ),
        migrations.AddField(
            model_name='actwriteoff',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
    ]
