# Generated by Django 2.2 on 2020-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0084_auto_20200406_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paperinvoice',
            old_name='date_extracts',
            new_name='date_invoice',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='confidant',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='date_power_of_attorney',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='freight_carrier',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='number_provider',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='power_of_attorney',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='paperinvoice',
            name='year',
        ),
        migrations.AddField(
            model_name='paperinvoice',
            name='bin',
            field=models.CharField(default=12, max_length=12, verbose_name='БИН'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperinvoice',
            name='provider',
            field=models.CharField(blank=True, default='not', max_length=1000, verbose_name='Поставщик'),
            preserve_default=False,
        ),
    ]
