# Generated by Django 2.2 on 2020-04-07 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0085_auto_20200407_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinvoice',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата накладной'),
        ),
    ]
