# Generated by Django 2.2 on 2020-04-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0086_auto_20200407_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinvoice',
            name='date',
            field=models.DateField(verbose_name='Дата накладной'),
        ),
    ]
