# Generated by Django 2.2 on 2020-04-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0090_auto_20200409_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberbooks',
            name='on_hands',
        ),
        migrations.AddField(
            model_name='numberbooks',
            name='summ',
            field=models.IntegerField(blank=True, default=0, verbose_name='сумма'),
        ),
        migrations.DeleteModel(
            name='AmountBooksStudents',
        ),
    ]
