# Generated by Django 2.2 on 2020-04-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0091_auto_20200415_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='summ',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='editionactwrite',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='editioninvoice',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='editionpaperinvoice',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='сумма'),
        ),
    ]
