# Generated by Django 2.2 on 2020-04-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0092_auto_20200415_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpense',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='количество'),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='summ',
            field=models.IntegerField(blank=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='type_of_movement',
            field=models.IntegerField(blank=True, default=0, verbose_name='вид движения'),
        ),
    ]
