# Generated by Django 2.2 on 2020-04-21 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0095_auto_20200416_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='number_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schol_library.NumberBooks'),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
