# Generated by Django 2.2 on 2020-04-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0096_auto_20200421_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Остаток'), (2, 'Приход'), (3, 'Остаток')], null=True),
        ),
    ]
