# Generated by Django 2.2 on 2020-04-22 07:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0097_incomeexpense_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actwriteoff',
            name='date_write',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 4, 22, 7, 22, 3, 617370, tzinfo=utc), verbose_name='дата на списание'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paperinvoice',
            name='date_invoice',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='дата счет фактуры'),
            preserve_default=False,
        ),
    ]
