# Generated by Django 2.2 on 2020-04-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0098_auto_20200422_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editionactwrite',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='editionpaperinvoice',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='сумма'),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='summ',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
    ]
