# Generated by Django 2.2 on 2020-04-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0099_auto_20200422_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editioninvoice',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
    ]
