# Generated by Django 2.2 on 2020-04-22 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0100_auto_20200422_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paperinvoice',
            name='bin',
        ),
    ]
