# Generated by Django 2.2 on 2020-04-22 09:47

from django.db import migrations, models
import schol_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0101_remove_paperinvoice_bin'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperinvoice',
            name='bin',
            field=models.IntegerField(default=0, validators=[schol_library.models.validate_bin_length], verbose_name='БИН'),
        ),
    ]
