# Generated by Django 2.2 on 2020-04-22 10:00

from django.db import migrations, models
import schol_library.models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0102_paperinvoice_bin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperinvoice',
            name='bin',
            field=models.BigIntegerField(default=0, validators=[schol_library.models.validate_bin_length], verbose_name='БИН'),
        ),
    ]
