# Generated by Django 2.2 on 2020-04-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0103_auto_20200422_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeexpense',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата накладной'),
        ),
    ]
