# Generated by Django 2.2 on 2020-04-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0104_incomeexpense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionactwrite',
            name='income',
            field=models.IntegerField(blank=True, default=0, verbose_name='id_прихода'),
        ),
        migrations.AddField(
            model_name='editionactwrite',
            name='income_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='id_прихода'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='income',
            field=models.IntegerField(blank=True, default=0, verbose_name='id_прихода'),
        ),
        migrations.AddField(
            model_name='incomeexpense',
            name='income_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='Тип приходного документа'),
        ),
        migrations.AlterField(
            model_name='incomeexpense',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Остаток'), (2, 'Приход'), (3, 'Расход')], null=True),
        ),
        migrations.AlterField(
            model_name='paperinvoice',
            name='idx',
            field=models.CharField(blank=True, default='Нет номера на накладной', max_length=300, verbose_name='Номер накладной'),
        ),
    ]
