# Generated by Django 2.2 on 2020-04-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0107_auto_20200424_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionactwrite',
            name='price',
            field=models.FloatField(blank=True, default=0, verbose_name='Цена'),
        ),
    ]
