# Generated by Django 2.2 on 2020-04-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0109_actwriteoff_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editionactwrite',
            unique_together={('invoice', 'edition', 'income', 'income_type')},
        ),
    ]
