# Generated by Django 2.2 on 2020-04-28 04:09

from django.db import migrations


def kill_reg(apps, sch_editor):
    Register = apps.get_model('school_library', 'IncomeExpense')
    Prihod = apps.get_model('school_library', 'PaperInvoice')

    d = Register.objects.all().delete()
    p = Prihod.objects.filter(status=True)
    for item in p:
        item.save()
        print(item.pk)


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0110_auto_20200427_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numberbooks',
            name='in_register',
        ),
    ]
