# Generated by Django 2.2 on 2020-04-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0111_remove_numberbooks_in_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberbooks',
            name='in_register',
            field=models.BooleanField(default=False, editable=False, verbose_name='В регистре'),
        ),
    ]
