# Generated by Django 2.2 on 2020-04-28 04:30

from django.db import migrations


def kill_reg(apps, sch_editor):
    Register = apps.get_model('schol_library', 'IncomeExpense')
    Prihod = apps.get_model('schol_library', 'PaperInvoice')

    d = Register.objects.all().delete()

    p = Prihod.objects.filter(status=True)
    for item in p:
        item.save()
        print(item.pk)


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0112_numberbooks_in_register'),
    ]

    operations = [

        migrations.RunPython(kill_reg),

        migrations.RemoveField(
            model_name='numberbooks',
            name='in_register',
        ),
    ]
