# Generated by Django 2.2 on 2020-04-28 06:21

from django.db import migrations


def kill_reg(apps, sch_editor):
    NumberBooks = apps.get_model('schol_library', 'NumberBooks')

    for i in NumberBooks.objects.filter(in_register=False):
        i.is_record_to_register = True
        print('reg')
        i.save()


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0114_numberbooks_in_register'),
    ]

    operations = [
        migrations.RunPython(kill_reg)
    ]
