# Generated by Django 2.2 on 2020-04-28 07:00

from django.db import migrations, models


def kill_reg(apps, sch_editor):
    Register = apps.get_model('schol_library', 'IncomeExpense')
    Prihod = apps.get_model('schol_library', 'PaperInvoice')

    d = Register.objects.all().delete()

    p = Prihod.objects.filter(status=True)
    for item in p:
        item.save()
        print(item.pk)


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0119_auto_20200428_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='numberbooks',
            name='in_register',
            field=models.BooleanField(default=False, verbose_name='В регистре'),
        ),

        migrations.RunPython(kill_reg)
    ]
