# Generated by Django 2.2 on 2020-04-28 07:12

from django.db import migrations


def skill_reg(apps, sch_editor):
    NumberBooks = apps.get_model('schol_library', 'NumberBooks')

    d = NumberBooks.objects.filter(in_register=False)
    it = 0
    for i in d:
        i.is_record_to_register = True

        i.save()

        it = it + 1
        print(it)


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0120_numberbooks_in_register'),
    ]

    operations = [
        migrations.RunPython(skill_reg)
    ]
