# Generated by Django 2.2 on 2020-04-28 06:51

from django.db import migrations, models
import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType

def add_initial_balance(apps, sch_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0123_initialbalance_date'),
    ]

    operations = [
        migrations.RunPython(add_initial_balance)
    ]
