# Generated by Django 2.2 on 2020-05-06 04:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0124_auto_20200505_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialbalance',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.AddField(
            model_name='initialbalance',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
