# Generated by Django 2.2 on 2020-05-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0127_booksorder_editionbooksorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='editionactwrite',
            name='has',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
        migrations.AddField(
            model_name='editionactwrite',
            name='summ',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма'),
        ),
    ]
