# Generated by Django 2.2 on 2020-05-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0128_auto_20200513_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='editionactwrite',
            name='has',
            field=models.FloatField(blank=True, default=0, verbose_name='Кол ост'),
        ),
        migrations.AlterField(
            model_name='editionactwrite',
            name='income_type',
            field=models.IntegerField(blank=True, default=0, verbose_name='id_типа_прихода'),
        ),
        migrations.AlterField(
            model_name='editionactwrite',
            name='summ',
            field=models.FloatField(blank=True, default=0, verbose_name='Сумма ост'),
        ),
    ]
