# Generated by Django 2.2 on 2020-05-14 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    #    ('portfoli', '0105_auto_20200514_1018'),
        ('schol_library', '0129_auto_20200514_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksRecall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='date_delete')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('quntity', models.IntegerField()),
                ('qunity_after_recall', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition')),
                (
                'order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schol_library.BooksOrder')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
