# Generated by Django 2.2 on 2020-05-14 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0130_booksrecall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booksrecall',
            old_name='qunity_after_recall',
            new_name='quanity_after_recall',
        ),
        migrations.RenameField(
            model_name='booksrecall',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
