# Generated by Django 2.2 on 2020-05-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0131_auto_20200514_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksrecall',
            name='quanity_after_recall',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
