# Generated by Django 2.2 on 2020-05-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
     #   ('portfoli', '0108_auto_20200515_0814'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0132_auto_20200515_0814'),
    ]

    operations = [

    ]
