# Generated by Django 2.2 on 2020-05-15 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0133_actwriteoff2_editionactwrite2'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editionactwrite',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='editionactwrite',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='editionactwrite',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='ActWriteOff',
        ),
        migrations.DeleteModel(
            name='EditionActWrite',
        ),
    ]
