# Generated by Django 2.2 on 2020-05-17 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0133_auto_20200515_1505'),
        ('schol_library', '0137_actwriteoff_editionactwrite'),
    ]

    operations = [
    ]
