# Generated by Django 2.2 on 2020-05-17 01:40
from django.db import migrations, models
import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType


# def add_initial_balance(apps, sch_editor):
#     NumberBooks = apps.get_model('schol_library', 'NumberBooks')
#     InitialBalance = apps.get_model('schol_library', 'InitialBalance')
#     EditionInitialBalance = apps.get_model('schol_library', 'EditionInitialBalance')
#     IncomeExpense = apps.get_model('schol_library', 'IncomeExpense')
#     PaperInvoice = apps.get_model('schol_library', 'PaperInvoice')
#     AlmaMater = apps.get_model('portfoli', 'AlmaMater')
#
#     sc = AlmaMater.objects.all()
#     d = NumberBooks.objects.all()
#     for i in sc:
#         nb = NumberBooks.objects.filter(school=i, deleted=False).exclude(edition=None)
#
#         ib = InitialBalance()
#         date = datetime.datetime.strptime('12/31/19', '%m/%d/%y')
#         ib.school = i
#         ib.date = date
#         try:
#             ib.author = i.librarian_user.user
#         except:
#             ib.author_id = 7
#         ib.save()
#         id_list = nb.values_list('id', flat=True)
#         resitr_recs = IncomeExpense.objects.filter(number_book_id__in=id_list).delete()
#         for el in nb:
#             eib = EditionInitialBalance()
#             eib.invoice = ib
#             eib.edition = el.edition
#             eib.quantity = el.summ
#             eib.amount = el.amounts
#             eib.save()
#             el.deleted = True
#             el.save()
#
#         ib.save()
#         print(ib)
class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0138_merge_20200517_0737'),
    ]

    operations = [

      #  migrations.RunPython(add_initial_balance)

    ]
