# Generated by Django 2.2 on 2020-05-17 01:42

from django.db import migrations, models
import datetime
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType




class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0139_auto_20200517_0740'),
    ]

    operations = [

    ]
