# Generated by Django 2.2 on 2020-05-17 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0141_auto_20200517_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='liter',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='liter',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added'),
        ),
        migrations.AddField(
            model_name='liter',
            name='date_delete',
            field=models.DateField(blank=True, null=True, verbose_name='date_delete'),
        ),
        migrations.AddField(
            model_name='liter',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='liter',
            name='exchange',
            field=models.BooleanField(default=False),
        ),
    ]
