# Generated by Django 2.2 on 2020-05-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0143_schooltitulhead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooltitulhead',
            options={'verbose_name': 'Титул школы заголовок', 'verbose_name_plural': 'Титулы школы заголовки'},
        ),
    ]
