# Generated by Django 2.2 on 2020-05-17 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0144_auto_20200517_0828'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitul',
            name='titul_head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_titul', to='schol_library.SchoolTitulHead'),
        ),
    ]
