# Generated by Django 2.2 on 2020-05-17 03:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0145_schooltitul_titul_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitulhead',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2020, 5, 17, 3, 20, 56, 867297, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
