# Generated by Django 2.2 on 2020-05-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0146_schooltitulhead_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitulhead',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
    ]
