# Generated by Django 2.2 on 2020-05-17 12:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0147_schooltitulhead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooltitul',
            name='class_teacher',
        ),
    ]
