# Generated by Django 2.2 on 2020-05-18 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
   #     ('portfoli', '0110_auto_20200518_1447'),
        ('schol_library', '0148_remove_schooltitul_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefcase',
            name='status',
            field=models.BooleanField(blank=True, default=False, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='briefcase',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects',
                                    verbose_name='Учебный год'),
        ),
    ]
