# Generated by Django 2.2 on 2020-05-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0161_auto_20200518_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editioninitialbalance',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions_invoice', to='schol_library.InitialBalance', verbose_name='Начальный остаток'),
        ),
    ]
