# Generated by Django 2.2 on 2020-05-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0162_auto_20200518_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefcase',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
