# Generated by Django 2.2 on 2020-05-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0163_briefcase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='briefcase',
            name='study_direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='schol_library.StudyDirections', verbose_name='направления обучения'),
        ),
    ]
