# Generated by Django 2.2 on 2020-05-26 08:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0165_auto_20200526_1420'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='editioninitialbalance',
            unique_together=set(),
        ),
    ]
