# Generated by Django 2.2 on 2020-05-26 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0166_auto_20200526_1432'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkidrequestedition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='editionbooksorder',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='numberbooks',
            unique_together=set(),
        ),
    ]
