# Generated by Django 2.2 on 2020-05-26 08:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
     #   ('portfoli', '0112_auto_20200526_1420'),
        ('schol_library', '0167_auto_20200526_1433'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkidrequestedition',
            unique_together={('request_edition', 'school')},
        ),
    ]
