# Generated by Django 2.2 on 2020-05-27 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0168_auto_20200526_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksrecall',
            name='order',
        ),
    ]
