# Generated by Django 2.2 on 2020-05-27 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
     #   ('portfoli', '0113_auto_20200527_0751'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0169_remove_booksrecall_order'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='BooksOrder1',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
        #         ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
        #         ('date_delete', models.DateField(blank=True, null=True, verbose_name='date_delete')),
        #         ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
        #         ('exchange', models.BooleanField(default=False)),
        #         ('date', models.DateField(null=True, verbose_name='Дата ввода остатков')),
        #         ('status', models.BooleanField(default=False)),
        #         ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
        #         ('school', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
        #     ],
        #     options={
        #         'verbose_name': 'Заявка на книги',
        #         'verbose_name_plural': 'Заявки на книги',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='EditionBooksOrder1',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('quantity', models.IntegerField(blank=True, default=0, verbose_name='количество')),
        #         ('edition', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition', verbose_name='издание')),
        #         ('invoice', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='editions_invoice111', to='schol_library.BooksOrder1', verbose_name='Заявка на книги')),
        #     ],
        #     options={
        #         'verbose_name': 'Книги для заявки',
        #         'verbose_name_plural': 'Книги для заявок',
        #         'ordering': ['id'],
        #     },
        # ),
    ]
