# Generated by Django 2.2 on 2020-05-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0170_booksorder1_editionbooksorder1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editionbooksorder',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='editionbooksorder',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='BooksOrder',
        ),
        migrations.DeleteModel(
            name='EditionBooksOrder',
        ),
    ]
