# Generated by Django 2.2 on 2020-05-27 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0172_booksorder_editionbooksorder'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='booksrecall',
        #     name='order',
        #     field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schol_library.BooksOrder'),
        #     preserve_default=False,
        # ),
    ]
