# Generated by Django 2.2 on 2020-05-27 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0176_actwriteoff_editionactwrite'),
    ]

    operations = [

        migrations.AddField(
            model_name='booksrecall',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.BooksOrder'),
        ),
    ]
