# Generated by Django 2.2 on 2020-05-27 05:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0179_actwriteoff_editionactwrite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooltitul',
            name='study_direction',
        ),
    ]
