# Generated by Django 2.2 on 2020-05-29 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      #  ('portfoli', '0114_auto_20200529_0749'),
        ('schol_library', '0181_schooltitul_study_direction'),
    ]

    operations = [


    ]
