# Generated by Django 2.2 on 2020-05-30 08:37

from django.db import migrations


def set_study_direction(apps, sch_editor):
    StudyDirections = apps.get_model('schol_library', 'StudyDirections')
    SchoolTitul = apps.get_model('schol_library', 'SchoolTitul')
    Briefcase = apps.get_model('schol_library', 'Briefcase')


    sd = StudyDirections()
    sd.name_ru = 'Не указано'
    sd.save()

    t = SchoolTitul.objects.all()

    for item in t:
        item.study_direction = sd
        item.save()

    t = Briefcase.objects.all()

    for item in t:
        item.study_direction = sd
        item.save()




class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0184_booksorder_booksrecall_editionbooksorder'),
    ]

    operations = [
        migrations.RunPython(set_study_direction)
    ]
