# Generated by Django 2.2 on 2020-06-01 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    #    ('portfoli', '0115_auto_20200601_0932'),
        ('schol_library', '0185_auto_20200530_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksrecall',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BooksMovingHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='date_delete')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('date', models.DateField(null=True, verbose_name='Дата перемещения')),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipient_school',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_school',
                                   to='portfoli.AlmaMater')),
                ('sender_school',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_school',
                                   to='portfoli.AlmaMater')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BooksMovingEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Инвентарный номер')),
                ('quantity', models.IntegerField(blank=True, default=0, verbose_name='количество')),
                ('amount', models.FloatField(blank=True, default=0, verbose_name='Сумма')),
                ('has', models.FloatField(blank=True, default=0, verbose_name='Кол ост')),
                ('summ', models.FloatField(blank=True, default=0, verbose_name='Сумма ост')),
                ('price', models.FloatField(blank=True, default=0, verbose_name='Цена')),
                ('income', models.IntegerField(blank=True, default=0, verbose_name='id_прихода')),
                ('income_type', models.IntegerField(blank=True, default=0, verbose_name='id_типа_прихода')),
                ('edition',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Edition',
                                   verbose_name='издание')),
                ('invoice',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions_invoice',
                                   to='schol_library.BooksMovingHead')),
            ],
            options={
                'verbose_name': 'Книга для перемещения',
                'verbose_name_plural': 'Книги для перемещения',
                'ordering': ['id'],
            },
        ),
    ]
