# Generated by Django 2.2 on 2020-06-01 06:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('schol_library', '0187_booksmovinghead_recall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksrecall',
            name='status',
        ),
    ]
