# Generated by Django 2.2 on 2020-10-25 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0188_remove_booksrecall_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmovingedition',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions_val', to='schol_library.BooksMovingHead'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='amount',
            field=models.FloatField(blank=True, default=0, verbose_name='сумма'),
        ),
    ]
