# Generated by Django 2.2 on 2021-04-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0190_auto_20210407_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltitulhead',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа'),
        ),
        migrations.AlterField(
            model_name='schooltitulhead',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год'),
        ),
    ]
