# Generated by Django 2.2 on 2021-04-21 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schol_library', '0191_auto_20210407_2156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liter',
            options={'ordering': ['sort'], 'verbose_name': 'Литер класса', 'verbose_name_plural': 'Литеры класса'},
        ),
        migrations.AddField(
            model_name='schooltitulhead',
            name='kurator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
