# Generated by Django 2.2 on 2021-04-21 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0192_auto_20210421_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edition',
            options={'ordering': ['klass__id', 'subject__sort', 'name'], 'verbose_name': 'издание', 'verbose_name_plural': 'издания'},
        ),
        migrations.AlterField(
            model_name='edition',
            name='cancellation_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.CancellationReason', verbose_name='причина отмены'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='funding_cycle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.FundingСycle', verbose_name='цикл финансирования'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='klass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс'),
        ),
        migrations.AlterField(
            model_name='edition',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык'),
        ),
    ]
