# Generated by Django 2.2 on 2021-04-29 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0003_auto_20210429_0855'),
        ('schol_library', '0193_auto_20210421_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolTitulPlannedHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date_added')),
                ('date_delete', models.DateField(blank=True, null=True, verbose_name='date_delete')),
                ('comment', models.CharField(blank=True, default='', max_length=1000, verbose_name='Comment')),
                ('exchange', models.BooleanField(default=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('students', models.IntegerField(default=0, verbose_name='количество учащихся')),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Статус')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.Klass', verbose_name='класс')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.Language', verbose_name='язык обучения')),
                ('liter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Liter', verbose_name='Название класса')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.AlmaMater', verbose_name='школа')),
                ('study_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.StudyDirections', verbose_name='направления обучения')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfoli.DateObjects', verbose_name='Учебный год')),
            ],
            options={
                'verbose_name': 'Титул школы заголовок',
                'verbose_name_plural': 'Титулы школы заголовки',
            },
        ),
    ]
