# Generated by Django 2.2 on 2021-04-29 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0004_auto_20210429_1745'),
        ('schol_library', '0194_schooltitulplannedhead'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooltitulplannedhead',
            options={'verbose_name': 'Плановый Титул школы заголовок', 'verbose_name_plural': 'Плановый Титулы школы заголовки'},
        ),
        migrations.AlterUniqueTogether(
            name='schooltitulhead',
            unique_together={('klass', 'school', 'liter', 'year', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='schooltitulplannedhead',
            unique_together={('klass', 'school', 'liter', 'year', 'status')},
        ),
    ]
