# Generated by Django 2.2 on 2021-04-30 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0006_auto_20210430_1557'),
        ('schol_library', '0196_auto_20210430_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooltitulhead',
            unique_together={('klass', 'school', 'liter', 'year', 'status')},
        ),
        migrations.AlterUniqueTogether(
            name='schooltitulplannedhead',
            unique_together={('klass', 'school', 'liter', 'year', 'status')},
        ),
    ]
