# Generated by Django 2.2 on 2021-05-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0197_auto_20210430_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schooltitulhead',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='schooltitulplannedhead',
            unique_together=set(),
        ),
    ]
