# Generated by Django 2.2 on 2021-05-03 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0198_auto_20210503_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitulplannedhead',
            name='percent',
            field=models.IntegerField(default=0, verbose_name='Процент'),
        ),

    ]
