# Generated by Django 2.2 on 2021-05-03 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0199_auto_20210503_0921'),
    ]

    operations = [

    ]
