# Generated by Django 2.2 on 2021-05-03 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0200_auto_20210503_0925'),
    ]

    operations = [

    ]
