# Generated by Django 2.2 on 2021-05-03 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0201_remove_schooltitulplannedhead_titul'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitulplannedhead',
            name='titul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.SchoolTitulHead', verbose_name='Титульный список'),
        ),
    ]
