# Generated by Django 2.2 on 2021-05-03 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0202_schooltitulplannedhead_titul'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooltitulplannedhead',
            name='percent',
            field=models.IntegerField(blank=True, default=0, verbose_name='Процент'),
        ),
    ]
