# Generated by Django 2.2 on 2021-06-07 11:33

from django.db import migrations

def set_comment(apps, schema_editor):
    SchoolTitulPlannedHead =apps.get_model('schol_library','SchoolTitulPlannedHead')

    pt = SchoolTitulPlannedHead.objects.all()
    for item in pt:
        if item.comment == '':
            if not item.titul is None:
                item.comment = item.titul.comment
                print(str(item.pk))
                item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0203_auto_20210503_0933'),
    ]

    operations = [
        migrations.RunPython(set_comment)
    ]
