# Generated by Django 2.2 on 2021-06-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0204_auto_20210607_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatVer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ver', models.CharField(default='0', max_length=255)),
            ],
        ),
    ]
