# Generated by Django 2.2 on 2021-06-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0205_catver'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooltitulhead',
            name='briefcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Briefcase', verbose_name='Титульный список'),
        ),
        migrations.AddField(
            model_name='schooltitulplannedhead',
            name='briefcase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schol_library.Briefcase', verbose_name='Титульный список'),
        ),
    ]
