# Generated by Django 2.2 on 2021-07-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schol_library', '0206_auto_20210610_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoredition',
            name='name',
            field=models.CharField(default='', max_length=500, verbose_name='автор'),
        ),
    ]
